# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a9f45027c0a6b8b8036b357165b24e105c8b4a28e9dcfe36cb2a51873914e0f799cc7376259d57365206c2734a4b4ee8d9bd5ce154786b7c695eb1f13da0846

test:
  secret_key_base: f38b5a8cacdc9a8d0769b61721d3784566d4fb9944f9ef73292f6ee960b2c247f557ca4f81f2d9d8fd3f3bf8861b128efdb74fad695068801a2697c9bbe5e1b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
